version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        networks:
            - watcher-network
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_KEY=base64:55Pv+tzpBfTAukEbiN6I/478daedJXf8d3VcnHYTJQk=
            - APP_DEBUG=true
            - APP_URL=http://localhost:8000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=mydb
            - DB_USERNAME=myuser
            - DB_PASSWORD=mypassword

    db:
        image: mariadb:10.5
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - watcher-network

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - watcher-network

volumes:
    db_data:

networks:
    watcher-network:
        driver: bridge
